### ISSUE TITLE
Investigate whether we can remove attributes

### ISSUE THREAD

**Issue by supermitsuba** [QuickenLoans/RAMLsharp#11]
I would love to remove custom attributes, if we can.  Right now, there is not an easy way to find Header and ResponseBody information in apidescriptors, but can we remove these attributes?

One way we could get ResponseBodies is by using example for 200 response bodies, but is there a way to describe error status codes from exceptions?

Please look seeing if we can represent headers and response bodies without the need for attributes.  If so, it may be worth making new issues for them.

**Comment by daleardi** [comment]
https://msdn.microsoft.com/en-us/library/5ast78ax.aspx

**Comment by supermitsuba** [comment]
no, still need it for 400s, 500s
