### ISSUE TITLE
URI parameters are duplicated

### ISSUE THREAD

**Issue by supermitsuba** [QuickenLoans/RAMLsharp#14]
If you create a sample web api, the URI parameters are created in both the URI parameter section and in each verb section.  This causes errors and needs to be in one or the other.

**Comment by jcichoski** [comment]
I would like to look into this, let me know if you have time to talk about it. I am unsure where to start, and I could learn a quite a bit by talking to you about it.

**Comment by supermitsuba** [comment]
This is caused by URI and Query String parameters being mixed in together.

**Comment by supermitsuba** [comment]
split out the query string parameters and uri parameters.  Keeping track of the first instance we use the uri parameters to stop the duplication
