### ISSUE TITLE
Fails to generate correct uriParameters for [FromUri] object

### ISSUE THREAD

**Issue by izmailoff** [QuickenLoans/RAMLsharp#24]
Hi all,

I have the following API:

    [Route("list")]
    [HttpGet]
    public HttpResponseMessage GetSomething([FromUri]BunchOfFields searchRequest)

and class:

    class BunchOfFields { public string field1 {get;set}; public int field2 {get;set;} }

for which generated RAML looks like this:

      get:
        description:
    /list?field1={Field1}&field2={Field2}:
      uriParameters:
          searchRequest:
            type: string
            required: false
            description:
            example: |

As you can see the URL with placeholders looks correct, but the `uriParameters` has a type of `string` and it's a single parameter. (C# converts a class to multiple parameters for Web API, for example: http://www.c-sharpcorner.com/UploadFile/2b481f/parameter-binding-in-Asp-Net-web-api/)

p.s. The symptoms are:
I'm getting this error: "Error while importing RAML: searchRequest uri parameter unused" when trying to import generated RAML into Postman.

Thanks,
Aleksey

**Comment by supermitsuba** [comment]
Thanks for posting this bug!  It's interesting to note that in RAML 0.8, they only had a concept of primitive types.  But this looks like it isn't picking up the uri parameters correctly.  I will take a look at the code and see what I can help with.

**Comment by supermitsuba** [comment]
The issue stems from the Web API helper classes.  The URL parses the model correctly, but not the ApiDescription.ParameterDescriptions object.  Will have to see how to work around that

**Comment by supermitsuba** [comment]
I think the best course of action would be to read properties of complex objects and make them parameters, provided they are acceptable primitives.  If it has nested complex objects, even ASP.net does not deconstruct them without the use of a media type formatter.  In that case there is nothing we could do, outside of introducing attributes or an interface to help this process.

**Comment by izmailoff** [comment]
Thanks a lot for the fix! Will be waiting for the nuget package to test it out.

**Comment by supermitsuba** [comment]
Package is out and should be ready to work.

**Comment by izmailoff** [comment]
Thanks for releasing the pakage so fast! For some reason I'm getting NullReferenceException in the same RAML code:

     var r = new RAMLMapper(this);
     Uri uri ...
     var data = r.WebApiToRamlModel(uri, "...", "1", "application/json", "This is a description"); // NRE

in the `WebApiToRamlModel` call. I tried in 2 different projects with the latest version (1.0.2).

**Comment by supermitsuba** [comment]
@izmailoff it worked for the few Web APIs I used it on, as well as all the unit tests pass from before.  Is there something more you could give me to diagnose the issue?  A stack trace or a skeleton of your web api might help out in debugging.  Also, considering this is open source and your project may not be, you could pull down my project and debug it locally.  Im sure then you would be able to see what the issue is and can help me resolve it.

**Comment by izmailoff** [comment]
Hi @supermitsuba here is the stack trace:

    at RAMLSharp.RAMLMapper.<GetUriParameters>b__c(ApiParameterDescription r) in z:\Users\jlowe\git\csharp\RAMLsharp\RAMLSharp\RamlMapper.cs:line 130
    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
    at RAMLSharp.RAMLMapper.GetUriParameters(ApiDescription description) in z:\Users\jlowe\git\csharp\RAMLsharp\RAMLSharp\RamlMapper.cs:line 139
    at RAMLSharp.RAMLMapper.WebApiToRamlModel(Uri baseUri, String title, String version, String defaultMediaTypes, String description) in z:\Users\jlowe\git\csharp\RAMLsharp\RAMLSharp\RamlMapper.cs:line 66
    at WebApplication.Controllers.RamlController.RAML() in C:\Users\lehab\Source\Repos\backend\Api\WebApplication\Controllers\RamlController.cs:line 22
    at lambda_method(Closure , Object , Object[] )
    at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
    at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
    at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

Thanks for responding so fast. I'll try to find time to debug it.

**Comment by supermitsuba** [comment]
looks like it is coming from this line:
```
.Where(r => r.Source == ApiParameterSource.FromUri && r.ParameterDescriptor.ParameterType.IsComplexModel())
```
I imagine it is from not checking for nulls on ParameterDescriptor and ParameterType.  Ill try to add some unit tests and see if i can reproduce it.

**Comment by supermitsuba** [comment]
Alright, I have fixed that issue.  Give it a whirl and let me know if it works for you.

**Comment by izmailoff** [comment]
Hi @supermitsuba , thanks for the fix again. I tried it and it properly unwraps a class argument into multiple primitive arguments. It does not throw any exceptions. I think this issue can be closed.

However, for optional URL arguments of primitive type it creates `HasValue` and `Value` arguments which is not correct. Here is an example:

C# code:

    GetSomething(long? someId = null)

Generated RAML:

      get:
        description: 
    /api/something/something?agreementId={someId}:
      uriParameters: 
          HasValue: 
            type: boolean
            required: true
            description: 
            example: |
                
          Value: 
            type: integer
            required: true
            description: 
            example: |

Thanks.

**Comment by supermitsuba** [comment]
Let me see what i can do about nullables.

**Comment by supermitsuba** [comment]
That should now be fixed too.  Although it will not mark the required field to false.  Ill make a new issue about that.  That should be it, have fun and let me know if you see anything else.
