### ISSUE TITLE
Create Auto Hosted Endpoint

### ISSUE THREAD

**Issue by supermitsuba** [QuickenLoans/RAMLsharp#6]
I would like to create an endpoint that automatically hosts the RAML document, without the need for the user to add code to host the file.

How we could do this is something that can be similar to ASP.net Help Pages, where an Area and controller is generated to host the RAML file.

Look at ASP.net Help Pages for ideas on how to create a /help page for a /raml page.

Link:  https://www.nuget.org/packages/Microsoft.AspNet.WebApi.HelpPage/5.2.3

**Comment by daleardi** [comment]
I looked into this and its pretty simple. When we create the nuget package we need to use convention based working directory and place the controller under the content folder. 

http://docs.nuget.org/create/creating-and-publishing-a-package#From_a_convention_based_working_directory

To include it in the namespace we need use a .pp file for our source and include  visual studio properties for the namespace. 

http://docs.nuget.org/create/configuration-file-and-source-code-transformations

**Comment by daleardi** [comment]
just making a note of this 
http://stackoverflow.com/questions/13242282/nuget-powershell-script-to-modify-global-asax-cs/13255356#13255356

**Comment by supermitsuba** [comment]
Looking at this more closely, we can add a new controller in the API.  The xml stuff cannot be added because of the Area stuff.  Areas are in MVC and I dont want to add that dependency.

**Comment by supermitsuba** [comment]
Added only the route.  Could not add code for xml documentation or areas to the project.  This will only work for C#
